[package]
name = "rustedge_agent"
version = "2.0.0"
edition = "2021"

[dependencies]
rust-bert = "0.23.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ndarray = "0.15"